### PR TITLE
adds missing declarations for static functions and moves static funct…

### PR DESCRIPTION
**Pull request by stefan-nu**
This modification aims to better separate the API with comments from implementation code.
Implements #921.
The functionality of the code was left unchanged.

### CODE REVIEW

**Comment by stefan-nu** [comment]
Could someone with access to a Linux build system tell me to result of 
`use: diff ./results/31.txt.sed scripts/Output/31.txt`

The script `/scripts/Test_more_Options.sh; ` is not happy with my changes.

**Comment by gmaurel** [comment]
Sorry, I have to modify the test, to prevent such a noise (next week!)
The problem are the different number width between your output and the reference.
Have a look to:
https://travis-ci.org/uncrustify/uncrustify/jobs/192133573
begins with line 4647
a difference indent_text(xxxx) vs. indent_text(xxx)
Make a copy of your output by using the ./scripts/Test_more_Options.sh to ./scripts/Output/31.txt
and push to the PR.

**Comment by mihaipopescu** [comment]
> I am working under Windows where the named script does not run.
That's why we need those scripts in python or something else.

Until then, did you tried Cygwin or Ubuntu Bash on Windows (anniversary update) ?

**Comment by gmaurel** [comment]
I have made some changes for the script.
Could you test again?

**Comment by stefan-nu** [comment]
Yes I did so, but the test still fails...

**Pull request merged**
