### PR TITLE
Minimal newlines after function body (fix #2787)

### LINKED ISSUE #2787: add newline after function, but don't remove multiple
I want this code:

```c
int foo()
{
    return 5;
}
int bar()
{
    return 3;
}


char test()
{
    return 'c';
}
```

to become:

```c
int foo()
{
    return 5;
}

int bar()
{
    return 3;
}


char test()
{
    return 'c';
}
```

But when I set `nl_after_func_body = 2`, two lines before `test()` becomes one. Is there other way?

### PR DESCRIPTION
**Pull request by Jorengarenar**

### CODE REVIEW

**Comment by micheleCTDEAdmin** [comment]
Hi @Jorengarenar
can you provide some background on this PR? What was the original problem (is there an issue logged for it) and what is that the PR is trying to achieve? Thank you

**Comment by Jorengarenar** [comment]
Hi @micheleCTDEAdmin!
Yes, there's a issue logged: #2787
To summarize: `nl_after_func_body` works as 'force', while `nl_min_after_func_body` will behave like 'add'.

**Comment by micheleCTDEAdmin** [comment]
Hi @Jorengarenar,
not sure you closed this by mistake or on purpose.
Sorry, it was a busy weekend and start of the week. Will have a look at this PR possibly tomorrow.

**Comment by Jorengarenar** [comment]
Hi @micheleCTDEAdmin,
Yes, it was intentional. I've thought I'll make also `nl_max_after_func_body`, so I'll send a new PR later :)

**Comment by micheleCTDEAdmin** [comment]
Ok thanks for the info.

**Pull request closed without merging**
