### PR TITLE
a new option to control the space between two strings

### LINKED ISSUE #4176: C : whitespace added between strings
My C code is formatted by uncrustify with a whitespace added between my strings but i don't want this whitespace between the SEP and "%%".

Original code:
```
void main()
{
  foo(" LIKE '%s"SEP"%%'");
}
```
Formatted:
```
void main()
{
  foo(" LIKE '%s"SEP "%%'"); // whitespace added
}
```
 
I tried replacing all "force" and "add" of "sp_" fields with "ignore" but the whitespace is always added.

It's a bug or i'm missing something in ths config file ?

### PR DESCRIPTION
**Pull request by guy-maurel**
fixes #4176 
replace PR #4180

### CODE REVIEW

**Comment by dev-pac** [comment]
it's ok for my use case #4176 but i get some weird result when i add a whitespace between "start" and SEP , a whitespace is added after SEP with sp_string_string = ignore

```
#define SEP "###"

void main()
{
  foo("start" SEP"end");
}
```
formatted :
```
#define SEP "###"

void main()
{
  foo("start" SEP" end");
}
```

**Comment by guy-maurel** [comment]
Please try:
`uncrustify -c dev-pac.cfg -f dev-pac-2.c -o out-2.c -p p-2.txt`

and have a look to p-2.txt
`#   5>               WORD       ...                    SEP`

Remember, uncrustify is not a compiler.
uncrustify doesn't interpret macros

**Comment by dev-pac** [comment]
> Please try: `uncrustify -c dev-pac.cfg -f dev-pac-2.c -o out-2.c -p p-2.txt`
> 
> and have a look to p-2.txt `# 5> WORD ... SEP`

Sorry, i don't understand this part of your comment.

For me the sp_string_string parameter should add/remove/ignore/force spaces between 2 strings so :

sp_string_string : add or force
 - input : ```"string1""string2""string3"```
 - expected : ```"string1" "string2" "string3"```

 - input : ```"string1" "string2""string3"```
 - expected : ```"string1" "string2" "string3"```


sp_string_string : remove
 - input : ```"string1" "string2" "string3"```
 - expected : ```"string1""string2""string3"```

 - input : ```"string1""string2" "string3"```
 - expected : ```"string1""string2""string3"```

**Comment by gmaurel** [comment]
This means: SEP is a WORD, not a STRING
Thanks for the test data. The output is:
```.log
Uncrustify_d-0.78.1-42-3c6863d79

do_source_file: Parsing: dev-1.c as language C
"string1" "string2" "string3"
do_source_file: Parsing: dev-2.c as language C
"string1" "string2" "string3"
do_source_file: Parsing: dev-3.c as language C
"string1""string2""string3"
do_source_file: Parsing: dev-4.c as language C
"string1""string2""string3"
```

**Review by gmaurel — APPROVED** [review]

**Pull request merged**
