### PR TITLE
update the descriptions for sp_after_for_colon and sp_before_for_colon

### PR DESCRIPTION
**Pull request by CDanU**
C++ range based for loops are supported.

------
ref: #1839

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
FWIW, #1852 is going to fix this also...

**Comment by CDanU** [comment]
Yes I know but that's going to take a while until we can merge it ... I'll fix the current CI complains later this night.

**Comment by mwoehlke-kitware** [comment]
> I'll fix the current CI complains later this night.

You forgot to `make update_cli_options` :smile:.

**Comment by CDanU** [comment]
Right I forgot about that one, it is indeed quiet helpful - even if I had to check the cmake files to find out that the target is only added for Release builds. Having the target always available but with an error message if the wrong build mode is set would be even better.

**Pull request merged**
