### PR TITLE
Correct the index.html file

### PR DESCRIPTION
**Pull request by guy-maurel**
about the mailing list.

### CODE REVIEW

**Comment by mihaipopescu** [comment]
We do have a mailing list on Google Groups https://groups.google.com/forum/m/#!forum/uncrustify

**Comment by mwoehlke-kitware** [comment]
> We do have a mailing list on Google Groups https://groups.google.com/forum/m/#!forum/uncrustify

We do? Why does no one know about this? Why, when I go there, do I get nothing but a blank page that tells me I have to be a member to participate, with a non-functional "Apply for membership"... er, thingy? (Ah... because that's the mobile version, which is apparently broken. https://groups.google.com/forum/#!forum/uncrustify is less broken.)

Do you know who admins that? The archives should be public, at least...

**Comment by mihaipopescu** [comment]
I made you guys owners. Feel free to make it public if not already.

**Comment by gmaurel** [comment]
I think it is not optimal that it is necessary to be a google user to have access.

**Comment by mwoehlke-kitware** [comment]
> I think it is not optimal that it is necessary to be a google user to have access.

As far as I can tell, we have the option of allowing only registered users (i.e. people with Google accounts) to send messages, or allowing *anyone* to send messages. The latter is potentially a spam issue, but I guess we could try it and see how it goes. I know there are other "open" lists hosted by Google Groups that seem to get by...

**Pull request merged**
