### PR TITLE
Fix issues related to C++11 parameter packs and others

### LINKED ISSUE #1783: Poor handling of parameter packs
Uncrustify doesn't seem to understand parameter packs. Consider this code:

```c++
template < typename A..., int B... >
struct foo : bar< A..., ( sizeof...(A) + B )... >;
```

...which gets mangled into:

```c++
template < typename A..., int B... >
struct foo : bar< A..., ( sizeof ... (A) +B ) ... >;
```

([debug.txt](https://github.com/uncrustify/uncrustify/files/2085035/debug.txt))

There are two definite problems here, and one possible problem. The most obvious is that `sizeof...` is not recognized as a single entity. I believe this is the cause of the undesired space added between `sizeof...` and the `(`, as well as between `sizeof` and `...`. (I suppose there "should" be an option whether or not to add space for the latter; personally, I don't want it.) The second is that space is undesirably added before the `...` which represents pack expansion; this should either have its own separate option or else be treated like any other postfix operator.

The *possible* issue is the space being removed before `B` in the second line. According to the debug output, this is being considered `POS`, which I guess means 'the unary `+` operator', where in actuality it is the binary addition operator (i.e. should be an `ARITH`). I mention this as "possible" because I suspect this only occurs because `(A)` is not being recognized as a function call, i.e. if `sizeof...` was being recognized as the same as `sizeof`, this would not happen. (A test with `sizeof...` replaced by `sizeof` seems to support this conclusion.)

[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastbin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Add options to suppress (or add) space on either side of the ellipsis in `sizeof ... (`. Add options to suppress (or add) space between a closing parenthesis and an ellipsis, or between a type and an ellipsis. Don't apply `sp_after_cast` to multiple words *inside of* the cast. Do a better job parsing the stuff after `sizeof...`.

~~This addresses some, but not all, aspects of #1783.~~ With the latest changes, this fixes #1783.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
It's not clear to me if this patch is complete. There seem to be other places where the new option maybe should be referenced, but it's not clear of those need to be updated by hand, or if they are generated somehow? Please let me know if there are any other changes I should be making in this PR; thanks!

**Comment by gmaurel** [comment]
You need to go to `tests/cli `and start `./test_cli_options.py`
You will get lot of errors. Have a look: you have introduced a new option --> some
help files need to be corrected:
```txt
Problem with results/help.txt
use: '--diff' to find out why results/help.txt output/help.txt are different
```

**Comment by mwoehlke-kitware** [comment]
> You need to go to `tests/cli` and start `./test_cli_options.py`.

Yes, that's the sort of thing I was wondering about... (BTW, is there any reason why CTest shouldn't run that?)

What about:

- `ChangeLog`
- `documentation/htdocs/*`
- `emscripten/libUncrustify.d.ts`
- `etc/*`

...do any of these also need updates? Are there tools for doing so automatically?

**Comment by CDanU** [comment]
> is there any reason why CTest shouldn't run that?)

We haven't thought about that, that would certainly be possible. Currently the `test_cli_options.py` script is a bit finicky as it need to be started from `tests/cli/` to generate the correct paths in the files that it is comparing.

You don't have to do any of those:
- **_documentation/htdocs/*_**       (here we aren't 100% set on what we want to do and how)
- **_emscripten/libUncrustify.d.ts_** (there is a update binding script that manually is triggered after a release)
- **_etc/*_**                                     (don't know, those look like example configs for users)


but you can add to the ChangeLog if you want to in order to help @gmaurel. He is usually updating that file before releasing a new version.

**Comment by mwoehlke-kitware** [comment]
> We haven't thought about that, that would certainly be possible. Currently the `test_cli_options.py` script is a bit finicky as it need to be started from `tests/cli/` to generate the correct paths in the files that it is comparing.

Given this is trivial to do with CTest (just give the appropriate `WORKING_DIRECTORY` to `add_test`), this seems if anything like an argument *in favor* of having this run via CTest :slightly_smiling_face:. It will be easier for the user, anyway. (Plus, that script has problems if `CMAKE_BINARY_DIR NOT` is not `${CMAKE_SOURCE_DIR}/build`...)

> but you can add to the ChangeLog if you want

Done. Thanks again!

**Comment by CDanU** [comment]
Ok, now only tests for your new options are missing.

**Comment by mwoehlke-kitware** [comment]
Okay, I'm working on tests, *but*... the tests I'd like to implement are broken right now, because they are basically covering all of #1783.

On a related note, is it acceptable to override `sp_sizeof_paren` to also control the space between `sizeof...` and `(`, or should I add a separate option for that?

**Comment by mwoehlke-kitware** [comment]
Another related note... I can fix some of my errors, but doing so breaks cpp_60034, because the spacing in `(Args...)` to use `sp_before_ellipsis` instead of `sp_after_type`. At least based on the option documentation, I feel like that's correct, but I'd appreciate a second opinion...

**Comment by mwoehlke-kitware** [comment]
Okay, I'm making progress... I decided to add `sp_type_ellipsis` rather than muck about too much with `sp_after_type`. Alas, this is causing 30922 to fail due to yet another pre-existing bug.

As a reminder, [the input for that](https://github.com/uncrustify/uncrustify/blob/ee8d609a608225d623a7aebb667de22d8c38dffa/tests/input/cpp/variadic-template.h) looks like:

```c++
template<int __i, int... _Indexes, typename _IdxHolder, typename...
_Elements>
struct __index_holder_impl<__i, __index_holder<_Indexes...>,
_IdxHolder, _Elements...>
{
typedef typename __index_holder_impl<__i + 1,
__index_holder<_Indexes...,
__i>,
_Elements...>::type type;
};
```

 As seen [here](https://github.com/uncrustify/uncrustify/files/2106953/debug.txt), for reasons I have not yet been able to determine, `_Indexes` and `_Elements` are recognized as `CT_TYPE`... *except* on the second-last line, where `_Elements` is `CT_WORD` instead, which is causing `sp_before_ellipsis` to be (wrongly) applied instead of `sp_type_ellipsis`.

**Comment by mwoehlke-kitware** [comment]
*Done!* :tada:. Whew :relieved:.

On its own, these changes break cpp-30922, however; #1809 is needed to prevent that.

**Comment by mwoehlke-kitware** [comment]
I have rebased this in light of #1802 and #1809... should pass CI now.

**Pull request merged**
