### PR TITLE
introduce functor

### LINKED ISSUE #3914: nl_func_call_paren should only remove a newline between the function name and first parenthesis that follow
[debug.txt](https://github.com/uncrustify/uncrustify/files/10262227/debug.txt)

Code to be uncrustifyed
```
void foo()
{
using namespace boost::program_options;
options_description desc("Allowed options");
desc.add_options()
    ("help,h", "produce help message")
    ("version,v", "print the version number")
    ("include-path,I", value< vector<string> >(), "include path")
    ("input-file,i", value<string>(), "input file");
}
```

Generated results:

```
void foo()
{
	using namespace boost::program_options;
	options_description desc("Allowed options");
	desc.add_options()("help,h", "produce help message")("version,v", "print the version number")("include-path,I", value< vector<string> >(), "include path")("input-file,i", value<string>(), "input file");
}

```

Expected results:

```
void foo()
{
	using namespace boost::program_options;
	options_description desc("Allowed options");
	desc.add_options()
	        ("help,h", "produce help message")
	        ("version,v", "print the version number")
	        ("include-path,I", value< vector<string> >(), "include path")
	        ("input-file,i", value<string>(), "input file");
}

```

Version:
`Uncrustify-0.76.0-21-e1ab302b`

We can see that boost::program_options's add_options() uses a kind-of fluent style API, but it appears uncrustify tries to remove all the newlines before every open parenthesis following the function name

### PR DESCRIPTION
**Pull request by guy-maurel**
fixes #3914

### CODE REVIEW

**Comment by micheleCTDEAdmin** [comment]
Hi @guy-maurel,
I did a test on approx 3200 files and this commit introduces some regressions as:
- in some places it changes how lines are split
- in some places it changes indentation
- in some places it adds unnecessary spaces around words or parenthesis

Most files are fine, but a handful of them suffers of the above regressions.
I think the easier way to share the issue is for you to clone this repo (https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest.git) and format all the files there with the following config file (https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest/src/branch/v47-32d9dbde/.uncrustify_tde.cfg).
Do this with current uncrustify master code and this commit and compare the different results. This will show the above regressions and will also provide additional test cases for a future fixed version.

**Comment by micheleCTDEAdmin** [comment]
Hi @guy-maurel,
let me know when you need a new test, I can do it (almost) anytime :-)

**Review by gmaurel — CHANGES_REQUESTED** [review]
doesn't work
try again later

**Comment by micheleCTDEAdmin** [comment]
Hi @guy-maurel 
I will try to do a big test later this week and feedback as well.

**Review by micheleCTDEAdmin — APPROVED** [review]
Looks good

**Comment by micheleCTDEAdmin** [comment]
> I will try to do a big test later this week and feedback as well.

Tested on my usual repo, no more regression!

**Review by gmaurel — APPROVED** [review]

**Pull request merged**
