### PR TITLE
Issue 1966: C comment end-marker */ mistaken for arithmetic operator

### PR DESCRIPTION
**Pull request by rblaine**
Ensure that comments which begin on the same line as a PP define
are recognized as comments, even when pp_ignore_define_body = True
Adjust the end column of the ignore'd CPP define body to be
accurately reflected in its chunk, in order to preserve spacing
between the define body and the beginning of the comment.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
Can you please also add a test? Also, your changes do not conform to uncrustify's code style. Please run CTest to verify that your changes are passing the test suite. (Right now they are not.)

**Comment by gmaurel** [comment]
@rblaine : anything new? A test?

**Comment by rblaine** [comment]
Haven't had the chance to yet, but am still planning on addressing the comments above.

**Comment by gmaurel** [comment]
Please resolve the conflicts

**Comment by andrey-starodubtsev** [comment]
Seems like it's already added in f5eae234 by @guy-maurel including test ([tests/input/cpp/Issue_1966.cpp](https://github.com/uncrustify/uncrustify/blob/master/tests/input/cpp/Issue_1966.cpp)) and can be safely closed.

**Comment by gmaurel** [comment]
OK. Thanks for the message.

**Pull request closed without merging**
