### PR TITLE
fix warning about uninitialized CMake variables

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addresses two CMake warnings when invoking CMake with `--warn-uninitialized`:

```
CMake Warning (dev) at tests/CMakeLists.txt:51 (if):
  uninitialized variable 'CMAKE_MATCH_2'
This warning is for project developers.  Use -Wno-dev to suppress it.
```

```
CMake Warning (dev) at tests/CMakeLists.txt:59 (if):
  uninitialized variable 'CMAKE_MATCH_6'
This warning is for project developers.  Use -Wno-dev to suppress it.
```

The two nested conditions can't be written as `if(cond1 AND cond2)` since CMake evaluates both conditions independent of the result of the first one.

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
I'm not sure this is worth merging... #1821 removes this code.

**Comment by mihaipopescu** [comment]
That PR is big (is it ready yet?) but as you wish. It would have been on you to fix the conflict.

**Comment by mwoehlke-kitware** [comment]
> It would have been on you to fix the conflict.

Sure, and if you're really impatient, that's okay too.

> is it ready yet?

IMHO, yes, if the proposed resolution to the re-run tests is acceptable.

**Comment by dirk-thomas** [comment]
If either of the patches makes it into the new released version I am happy.

**Comment by mwoehlke-kitware** [comment]
If you'd asked three days ago, I'd have said "yes", but I think #1821 is about ready; at least, I got the impression that @CDanU is basically satisfied aside from a bug with `-g` that I just fixed.

You still *could* merge this, it will just slow down #1821 a little due to needing to rebase it again.

I guess I'd say, wait a bit (i.e. a few hours, and not more than 24), and if it looks like #1821 is not as imminent as I am hoping, then go ahead and merge.

**Comment by mwoehlke-kitware** [comment]
The conflict is because this code no longer exists, due to #1821. Also due to #1821, the warning should be fixed. Therefore, closing this...

**Comment by mwoehlke-kitware** [comment]
(...but thanks for the patch anyway!)

**Pull request closed without merging**
