### PR TITLE
Add 'cmt_c_to_cpp_trailing_single_line' option

### PR DESCRIPTION
**Pull request by dundargoc**
This is an attempt to fix https://github.com/uncrustify/uncrustify/issues/3300.

### CODE REVIEW

**Comment by dundargoc** [comment]
Currently trying to decipher why the tests are failing.

**Comment by guy-maurel** [comment]
Please, have a look to https://github.com/dundargoc/uncrustify/actions
and activate the workflow

**Comment by dundargoc** [comment]
I added tests for the new option. I'm having trouble understanding what the error messages in the tests mean. I get errors such as

```
************************************
Problem (3) with result_path   is results/show_config.txt
                 expected_path is output/show_config.txt
************************************
```

**Comment by dundargoc** [comment]
@gmaurel @CDanU @mwoehlke-kitware I've added a test for the new option and the CI tests are green. Please take a look again.

**Review by gmaurel — APPROVED** [review]
Fine work. Thanks!

**Pull request merged**
