### PR TITLE
Use auto when declaring iterators.

### PR DESCRIPTION
**Pull request by dundargoc**
More readable in my opinion. Obviously subjective, don't hesitate to close if you disagree.

### CODE REVIEW

**Comment by micheleCTDE** [comment]
Personally I don't like the use of 'auto' and if it was for me, I would actually remove it rather than adding it. It makes the code less readable because you have no clue what type the variable is, unless you go and dig further.
So I defer to @guy-maurel whether he wants to merge this PR or not.

**Comment by dundargoc** [comment]
Eh, was mostly a suggestion. I'll close this :+1:

**Comment by micheleCTDE** [comment]
> Eh, was mostly a suggestion. I'll close this +1

I guess we can wait for @guy-maurel 's opinion. This is an open source project and Guy is the maintainer of it.
I expressed my opinion and reasons for it, but it does not mean it is "the law" :-)

**Comment by gmaurel** [comment]
I don't like "auto"
It is difficult to read it after some weeks.
Please, suppress "auto"

**Comment by dundargoc** [comment]
Yes, Fair enough :)

Should we close this then?

**Comment by dundargoc** [comment]
Your thoughts about the `auto` keyword makes sense. Thanks for the explanation :+1:

**Pull request closed without merging**
