### PR TITLE
Add feature to indent lines which contain only single newline

### PR DESCRIPTION
**Pull request by Krizai**
Solution to https://github.com/uncrustify/uncrustify/issues/1641

Added config parameter indent_single_newlines
Enabling this parameter will allow indenting single newline lines in the same way as normal lines.

### CODE REVIEW

**Comment by gmaurel** [comment]
Thanks for the PR.
Please change it to use the `argtype_e::AT_TFI` for the new option.
Change **newline** to **empty** line.
The value `AT_TFI` should be supported to get: "not any change" for the empty lines.
Provide an example (or more) to test the value `AT_TFI` on empty lines, lines with not enough spaces, lines with too much spaces.

**Comment by Krizai** [comment]
Didn't get an idea. What will T/F/I mean for this option?

**Comment by guy-maurel** [comment]
Many users wish to have a _NULL_ configuration file, to test one option at the time.
We don't have it just now. But it would be fine to work in this direction.
All new options should support that: false / true / ignore instead of false / true
For the new option you propose:
`false`: remove the spaces on empty lines,
`true`: add spaces on empty lines (according your proposal)
`ignore`: don't modify empty lines (even there are some spaces)

**Comment by Krizai** [comment]
Ignore will be tricky, as now we are collapsing all the newlines to one, so the only "easy" option I see is to save an array of the number of spaces for newline chunks.

**Comment by gmaurel** [comment]
You are right, the number of spaces is not known. Let us forget it and
Stay with the `argtype_e::AT_BOOL`
Please search for  better name for **newline** or **empty line** to make clear that the option works on line without token.

**Comment by Krizai** [comment]
What about "Indent empty lines - lines which contain only spaces before newline character"?

**Comment by gmaurel** [comment]
It would be fine.

**Comment by guy-maurel** [comment]
You need to use the test:` ./tests/cli/test_cli_options.py ` to check if all the tests are OK.

**Comment by gmaurel** [comment]
Sorry, it is not quite exact.
You need to use the test:
```
cd ./tests/cli
./test_cli_options.py
```
to check if all the tests are OK.

**Pull request closed without merging**
