### PR TITLE
Avoid blank line between case and return statement

### PR DESCRIPTION
**Pull request by geimer**
This PR proposes a fix for issue #2693. I'm not familiar enough with the `uncrustify` code base to judge whether this could have any adverse side effects, though the test suite still passes. However, this means that this particular case isn't covered by the test suite yet. Please let me know whether I should include my test case from the issue as a new test case, or whether I should modify one of the existing test cases.

### CODE REVIEW

**Comment by geimer** [comment]
It turns out that this is exactly what was proposed already in https://github.com/Unity-Technologies/uncrustify/commit/3b41d6ef7c32114ba9605ffd8b141830dca8212d (though using the helper function rather than using `pc->type` directly), but somehow a different solution got committed in https://github.com/uncrustify/uncrustify/commit/db6adb6c69b238746c60233a423eac3df02c4073. However, the test that was added at the same time does not use `nl_before_return`, and therefore the fact that the issue still persists went by unnoticed...

**Comment by MattBussing** [comment]
What is the ETA on this being merged?

**Comment by MattBussing** [comment]
Just a heads up this doesn't fix default in C#.
It edited a file and left this:

```
default:
      log....

      return;
```

So, this still needs work.

**Comment by geimer** [comment]
@MattBussing Could you please elaborate what you are expecting? I'm not entirely sure I understand your comment. With the following input
```
default:
    return;
```
and `nl_before_return = true`, current `master` inserts an extra blank line:
```
default:

    return;
```
Now, with the proposed change, this blank line is gone:
```
default:
    return;
```
If there is anything in between the `default` and the `return`, the `nl_before_return` still applies, that is,
```
default:
    Console.WrieLine("hello world\n");
    return;
```
will result in
```
default:
    Console.WrieLine("hello world\n");

    return;
```
if `nl_before_return = true` with both `master` and the proposed change, and stay unchanged if `nl_before_return = false`.  I believe that this is the intended behavior.

Having said that, extra newlines that are already in the input will indeed be kept, that is,
```
default:

    return;
```
will stay unchanged regardless of the `nl_before_return` setting. Likewise, for
```
default: return;
```
no newline will be inserted even with `nl_before_return = true`. It seems that `nl_after_case = false` prevents this.

**Pull request merged**
