### PR TITLE
Fix issue #3422

### PR DESCRIPTION
**Pull request by micheleCTDE**
One test was affected, referring to bug 612, but I am not able to find any reference to what that bug was. I propose we update the test, which is what I have done.

### CODE REVIEW

**Comment by micheleCTDE** [comment]
As an alternative solution, we could add an option to whether align/not align when multiple variable definitions are found on the same line. This should not require a change of the test for bug 612.
@guy-maurel What do you think? Add option or keep PR as is?

**Review by gmaurel — CHANGES_REQUESTED** [review]
NO support here

**Comment by micheleCTDE** [comment]
I tested on my ~3200 files test repo. Mostly good, but I see a regression with virtual functions declarations in 3 files. Will need more work, together with an option to enable/disable this.

**Comment by micheleCTDE** [comment]
I analysed the "egression in more detail.
The difference in those 3 files (out of ~3200 files) is with pointers to function, not with virtual functions.
In fact I would say it is not even a regression but a feature, because before this PR pointers to functions were aligned on return type but not on assignment, as in this example:

Original code:
```
int (*F_recv)(int, void*, unsigned long int, int) = 0L;
int (*F_send)(int, const void*, unsigned long int, int) = 0L;
int (*F_getsockname)(int, struct sockaddr*, ksocklen_t*) = 0L;
int (*F_getpeername)(int, struct sockaddr*, ksocklen_t*) = 0L;
int (*F_accept)(int, struct sockaddr*, ksocklen_t*) = 0L;
int (*F_select)(int, fd_set*, fd_set*, fd_set*, struct timeval*) = 0L;
int (*F_listen)(int, int) = 0L;
int (*F_bind)(int, const struct sockaddr*, ksocklen_t) = 0L;
int a = 0;
double bbbbb = 5.0;
double ccccccccccc = 5.0;
static double mylongclassname::dddddddddddddddd = 5.0;
```

Without this PR:
```
int           (*F_recv)(int, void*, unsigned long int, int) = 0L;
int           (*F_send)(int, const void*, unsigned long int, int) = 0L;
int           (*F_getsockname)(int, struct sockaddr*, ksocklen_t*) = 0L;
int           (*F_getpeername)(int, struct sockaddr*, ksocklen_t*) = 0L;
int           (*F_accept)(int, struct sockaddr*, ksocklen_t*) = 0L;
int           (*F_select)(int, fd_set*, fd_set*, fd_set*, struct timeval*) = 0L;
int           (*F_listen)(int, int) = 0L;
int           (*F_bind)(int, const struct sockaddr*, ksocklen_t) = 0L;
int           a                                 = 0;
double        bbbbb                             = 5.0;
double        ccccccccccc                       = 5.0;
static double mylongclassname::dddddddddddddddd = 5.0;
```

With this PR:
```
int           (*F_recv)(int, void*, unsigned long int, int)                = 0L;
int           (*F_send)(int, const void*, unsigned long int, int)          = 0L;
int           (*F_getsockname)(int, struct sockaddr*, ksocklen_t*)         = 0L;
int           (*F_getpeername)(int, struct sockaddr*, ksocklen_t*)         = 0L;
int           (*F_accept)(int, struct sockaddr*, ksocklen_t*)              = 0L;
int           (*F_select)(int, fd_set*, fd_set*, fd_set*, struct timeval*) = 0L;
int           (*F_listen)(int, int)                                        = 0L;
int           (*F_bind)(int, const struct sockaddr*, ksocklen_t)           = 0L;
int           a                                 = 0;
double        bbbbb                             = 5.0;
double        ccccccccccc                       = 5.0;
static double mylongclassname::dddddddddddddddd = 5.0;
```

You can see the side of the return type gets aligned, but the side of the assignment is not.
I would be inclined on merging this PR as is (or perhaps with an additional enable/disable option) and later work on adding more options for alignment of "pointers to function" enable/disable, alignment on return type side and alignment on assignment side.

What do you think @gmaurel?

**Comment by gmaurel** [comment]
yes

**Comment by micheleCTDE** [comment]
I have added the option 'align_assign_on_multi_var_defs' to allow the user to enable/disable this behavior. 
Default value is false, so no changes in behavior from the original uncrustify code. Changes on the test file for bug 612 are no longer required.
When the option is set to true, assignment will be aligned on the left most assign of a multi variable definition.

**Review by gmaurel — APPROVED** [review]

**Pull request merged**
