### PR TITLE
Fix string literal output

### PR DESCRIPTION
**Pull request by oleg-liatte**
Prevent replacing of tabs in string literals to spaces.
Example:
auto test = " 	  	abcdefg  		 ";

### CODE REVIEW

**Comment by oleg-liatte** [comment]
It appears that there are tests for the fixed case, and they expectedly fail, as they expect that uncrustify modifies string literals (which is incorrect for my point of view).

**Comment by CDanU** [comment]
Thanks for the PR, I get what you want to solve but I am not entirely convinced if passing an arg through multiple layers is the best solution. 
Honestly I think that add_char should not deal with removing the tab char in the first place. I will see if this situation can be improved somehow.

Related: #1873

**Comment by gmaurel** [comment]
@CDanU May I merge?

**Comment by CDanU** [comment]
Yes, you can actually merge it. I will refactor the output.cpp file soon after that.

**Pull request merged**
