### PR TITLE
Add some comments

### PR DESCRIPTION
**Pull request by guy-maurel**
As coveralls cannot trace these lines.

### CODE REVIEW

**Comment by guy-maurel** [comment]
I wanted to put a mark, not to search again (may be some months latter), why coveralls will complain.

**Comment by mwoehlke-kitware** [comment]
#1852 is going to make some of these irrelevant...

That said, we could use some tests for some of these (e.g. bad option values).

**Comment by gmaurel** [comment]
Some of the places are a test of the software itself, for which NO use case could be generated.

**Comment by mwoehlke-kitware** [comment]
> Some of the places are a test of the software itself, for which NO use case could be generated.

Those would be the parts that #1852 makes irrelevant. (More accurately, they don't *exist* in #1852, because there is no reason for them any more.)

**Pull request merged**
