### PR TITLE
Add sp_ptr_star_func_var option

### LINKED ISSUE #3376: Need option to control the space between the star and the name of a function pointer
Config file:

```
sp_before_ptr_star      = remove
sp_before_ptr_star_func = ignore
sp_after_ptr_star       = add
sp_after_ptr_star_func  = ignore
```

Test code:

```
int *ptr;
int (*func)();
```

Expected result:

```
int* ptr;
int (*func)();
```

Actual result:

```
int* ptr;
int (* func)();
```

### PR DESCRIPTION
**Pull request by alexhenrie**
Fixes #3376

### CODE REVIEW

**Comment by gmaurel** [comment]
Please, @alexhenrie have a look to the conflict

**Comment by alexhenrie** [comment]
The conflict is resolved.

**Review by gmaurel — APPROVED** [review]
Thanks

**Comment by alexhenrie** [comment]
Thank you!

**Pull request merged**
