### PR TITLE
Allow using an empty config by passing '-' as filename

### PR DESCRIPTION
**Pull request by CDanU**
... similarly to the -p option that also allows to pass a '-' in order to print debug output to stdout. 
This make scripting a bit easier.

### CODE REVIEW

**Comment by guy-maurel** [comment]
Please complete the documentation:
function usage in uncrustify.cpp
file man/uncrustify.1.in

**Comment by CDanU** [comment]
ref: #2261: Is there a reason why we don't show the flags in the debug output on windows?

**Comment by mwoehlke-kitware** [comment]
Is `/dev/null` too hard to type? (Note: in Python scripts, `os.devnull` can be used for portability.) I'm a little worried because `-` as a magic file name traditionally means "stdin". Also, what use cases are there for using an empty config, and would they be better served by making the config optional (as e.g. was already done when using `-p`)?

**Comment by mwoehlke-kitware** [comment]
> Is there a reason why we don't show the flags in the debug output on windows?

I wonder if it had something to do with format specifiers? That may no longer be an issue; flags are always `%llx`.

**Comment by CDanU** [comment]
> Is `/dev/null` too hard to type? (Note: in Python scripts, `os.devnull` can be used for portability.) I'm a little worried because `-` as a magic file name traditionally means "stdin". 

As far as I know the `-` is used for stdin **and** for stdout as well. We even use it for `-p` for stdout. 

> Also, what use cases are there for using an empty config, and would they be better served by making the config optional (as e.g. was already done when using `-p`)?

Making `-c` optional is error prone as a normal user needs to use a non empty config in almost all cases. The intent for using a empty config therefore should be clearly stated. While I agree that typing in `/dev/null` isn't complicated , this still makes it easier. I don't see a problem as the code change is minimal to support this feature.

**Pull request merged**
