### PR TITLE
rewrite mod_case_brace_add

### LINKED ISSUE #3040: Brace incorrectly added after a PP directive
This issue is similar to issue #3033 but I am reporting it separately since it shows up on a different config option. I wouldn't be surprised if the root cause is the same as the aforementioned issue.

uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3.
Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation :wink: )
- t1_out.cpp: output of the test run
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out.cpp"

uncrustify should add braces around "case" blocks, but when PP directive are presents, it seems to get confused.

Current output:
```
void main()
{
	switch (opcode)
	{
		case LocaleCompare:
		{
			return Number(localeCompare(s, a0.toString(exec)));

#ifndef KJS_PURE_ECMA
		}

		case Big:
		{
			result = String("<big>" + s + "</big>");
			break;
		}
#endif
	}
}
```

Note how the closing brace of the "case LocaleCompare:" block is added after the PP #ifndef instead than before it.

uncrustify does not report any error, but if you try to format the file a second time with "uncrustify -c test.cfg t1_out.cpp", the following errors are reported, which at least is a pointer that somethgin is wrong.
```
Parsing: t1_out_1st_pass.cpp as language CPP
indent_text(3862): size is 2
indent_text(3864): File: t1_out_1st_pass.cpp, open_line is 2, parent is NONE: Unmatched BRACE_OPEN
indent_text(3862): size is 2
indent_text(3864): File: t1_out_1st_pass.cpp, open_line is 2, parent is NONE: Unmatched BRACE_OPEN
```

[wrong_case_brace.zip](https://github.com/uncrustify/uncrustify/files/5756752/wrong_case_brace.zip)

### PR DESCRIPTION
**Pull request by guy-maurel**
fixes #3040

### CODE REVIEW

**Comment by micheleCTDE** [comment]
Good morning Guy, 
I tested the above commit on my usual test sample of 3200+ files.
It works much better than before and solves some additional things, but I also observed some regressions (at least one major and 3 minor).
Do you prefer I open separate issue reports for each of them and link them to here? Or do you prefer I report the problems here all together in a single test case?

**Comment by micheleCTDE** [comment]
Major regression described in issue 3044. Minor regression not yet posted.

**Comment by micheleCTDE** [comment]
Minor regression 1.

Test 1: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) 
Test 2: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) + commit from this PR #3048
NOTE: if you don't see the problem using the latest git version of uncrustify, please let me know and I will test accordingly.

Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation)
- t1_out_old.cpp: output of test 1
- t1_out_new.cpp: output of test 2
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out_old[/new].cpp" without and with the commit in PR #3048.

The original code has a comment on the same line of a break.
```
break;  // same line comment after a break
```
With this commit, the comment is incorrectly placed after the added closing brace.
```
			break;
		}         // same line comment after a break
```
while without this commit it was left in the right place
```
			break;  // same line comment after a break
		}
```

[PR3048-regression2.zip](https://github.com/uncrustify/uncrustify/files/5781629/PR3048-regression2.zip)

**Comment by micheleCTDE** [comment]
Minor regression 2.

Test 1: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) 
Test 2: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) + commit from this PR #3048
NOTE: if you don't see the problem using the latest git version of uncrustify, please let me know and I will test accordingly.

Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation)
- t1_out_old.cpp: output of test 1
- t1_out_new.cpp: output of test 2
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out_old[/new].cpp" without and with the commit in PR #3048.

Braces are correctly added and placed around the second case block, which is inside a #ifdef PP directive. Nevertheless the empty line is placed before #endif instead of after it.
Without the commit, the closing brace was wrongly placed but the empty line was in the right spot.
NOTE: code below was partially edited to better display here.
```
    case AF_INET:
    {
	return KInetSocketAddress::areEqualInet(*this, other, false);
    }

#ifdef AF_INET6
    case AF_INET6:
    {
	return KInetSocketAddress::areEqualInet6(*this, other, false);
    }
                            <<<<<<--------- This empty line should be after #endif and before the next case
#endif
    case AF_UNIX:  // AF_LOCAL
```

[PR3048-regression3.zip](https://github.com/uncrustify/uncrustify/files/5781675/PR3048-regression3.zip)

**Comment by micheleCTDE** [comment]
Minor regression 3.

Test 1: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) 
Test 2: uncrustify 0.72.0 + backport of commits 45681e88, 64d93e3 + fix for issue 3040 (both commits in PR #3043) + commit from this PR #3048
NOTE: if you don't see the problem using the latest git version of uncrustify, please let me know and I will test accordingly.

Files in attachment:
- t1_in.cpp: test file (subset of a real file, it would fail compilation)
- t1_out_old.cpp: output of test 1
- t1_out_new.cpp: output of test 2
- test.cfg: configuration used for the test

Step to reproduce: run "uncrustify -c test.cfg -f t1_in.cpp -o t1_out_old[/new].cpp" without and with the commit in PR #3048.

The original code has 3 switch blocks. uncrustify behaves as follow:

1. first switch: old version ok. new version places the "break" outside of the braces, which is not what I specified in the config. The problem seems to be related to the presence of a "return" before the break (see switch 2 for comparison)
```		case 3:
		{
			return i18n("The file '%1' was deleted by another program.").arg(url().prettyURL());
		}
		break;
```

2. second switch: ok with this commit, missing braces to last case/default in the old version

3. third switch: ok with this commit, "break" placed after the closing brace with the old version

[PR3048-regression5.zip](https://github.com/uncrustify/uncrustify/files/5782147/PR3048-regression5.zip)

**Comment by micheleCTDE** [comment]
That it is for the time being. There may be more regressions, but I guess it is better to fix these minor 3 and the major one I have described in issue #3044 (two difference scenarios) before further testing ;-)

**Comment by guy-maurel** [comment]
Please, don't use this any more.
Wait for the next PR

**Comment by micheleCTDE** [comment]
Sure. Will wait and then test when ready :+1:

**Comment by guy-maurel** [comment]
PR #3050 is a bugfix proposal, for the first part of the issue.
Please test it and report.

**Comment by micheleCTDE** [comment]
> PR #3050 is a bugfix proposal, for the first part of the issue.
> Please test it and report.

Thanks Guy.
Please see comment on PR #3050

**Comment by guy-maurel** [comment]
see you latter with a new PR

**Comment by guy-maurel** [comment]
PR #3056 is a bugfix proposal.
Please test it and report.

**Comment by micheleCTDE** [comment]
See comments in PR #3056. As additional info, regression [2](https://github.com/uncrustify/uncrustify/pull/3048#issuecomment-756102903) and [3](https://github.com/uncrustify/uncrustify/pull/3048#issuecomment-756152587) are still a problem, while 1 and 4 are now fixed.

**Comment by micheleCTDE** [comment]
Minor regression 1 is now documented as a separate issue #3058

**Pull request closed without merging**
