### PR TITLE
Fix typo in docs for indent_ternary_operator

### PR DESCRIPTION
**Pull request by fwojcik**
This just more accurately describes what the '1' option does.

### CODE REVIEW

**Review by micheleCTDE — CHANGES_REQUESTED** [review]
Although changes in the comment would be propagated to other files when making a release, it is always better to keep files in sync if possible.
Whenever an option is modified/added (including comments), there are a bunch of files to update (for example etc/defaults.cfg). Suggest you look up for the existing places of a comment and then modify accordingly.

**Comment by fwojcik** [comment]
Hmm. I cannot seem to find any documentation on this. Are the extra files in, say, commit d3768757d3f4cddb42d916a9ba75a785f0f6a972 a complete list? If so, I'll update this PR as well as #3797. 

You say that this would be done as part of a release. Is there any existing automation for this process? It seems like it really needs it.

**Comment by gmaurel** [comment]
Have a look to:
https://github.com/uncrustify/uncrustify/pull/3773#issuecomment-1206001431
and use scripts/release_tool.py  update build/uncrustify

**Comment by fwojcik** [comment]
Great, thanks!

**Review by micheleCTDEAdmin — APPROVED** [review]
Looks good, thanks!

**Review by micheleCTDE — APPROVED** [review]

**Pull request merged**
