### PR TITLE
Make git version string generation optional

### PR DESCRIPTION
**Pull request by CDanU**
use `cmake -DNoGitVersion=True ...` to disable it.

### CODE REVIEW

**Comment by CDanU** [comment]
ref: #1177

**Comment by guy-maurel** [comment]
Could it be wise to use `CMAKE_SYSTEM_NAME` ?

**Comment by CDanU** [comment]
I could include that, but personally I don't see the point as we don't use OS related functions much and those that we do use, worked without a flaw up to this point.

**Comment by guy-maurel** [comment]
Which one is the one we need: #1175 or #1179 ?

**Comment by CDanU** [comment]
This, the other one can be closed.

**Pull request merged**
