### PR TITLE
[DO NOT MERGE] Debugging #1852

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
This PR is to keep my debugging experiements separated as I try to figure out why apparently `make_option_enum.py` is getting stuck in the appveyor builds. (It works fine on my local Windows machine :cry:.)

### CODE REVIEW

**Comment by mihaipopescu** [comment]
It says:
> Build execution time has reached the maximum allowed time for your plan (60 minutes).

so strange.

**Comment by mwoehlke-kitware** [comment]
> Try using `''` instead of `b''` as sentinel to iter.

Aaaaack, you are right, thanks! It's a python 2 vs 3 thing. (I can reproduce locally if I switch my build to using Python 3.)

I wish I still knew what SO question I dug up that trick from, so I could write a grumpy, cautionary comment...

**Comment by mwoehlke-kitware** [comment]
Joy... Python is still going out to lunch... only happening on CI; I can't reproduce locally :cry:, even with the same version of Python.

**Comment by mwoehlke-kitware** [comment]
Hmm... well, news, anyway... some interaction with #2016 is causing things to go sideways. (Also, it looks like there are some bugs in the new `universalindentgui.cpp`, so I suppose that test is being useful.) At any rate, possibly explains why I was unable to reproduce locally...

**Pull request closed without merging**
