### PR TITLE
the function pointer is itself a function argument

### LINKED ISSUE #3259: sp_after_tparen_close doesn't work if function pointer is itself a function argument
Config file:

```
sp_after_tparen_close = add
```

Test code (adapted from [tests/input/c/i2c-core.c](https://github.com/uncrustify/uncrustify/blob/master/tests/input/c/i2c-core.c#L664)):

```
int (*found_proc)(struct i2c_adapter *, int, int);

static int i2c_probe_address(struct i2c_adapter *adapter, int addr, int kind,
			     int (*found_proc)(struct i2c_adapter *, int, int));
```

Expected output:

```
int (*found_proc) (struct i2c_adapter *, int, int);

static int i2c_probe_address(struct i2c_adapter *adapter, int addr, int kind,
                             int (*found_proc) (struct i2c_adapter *, int, int));
```

Actual output:

```
int (*found_proc) (struct i2c_adapter *, int, int);

static int i2c_probe_address(struct i2c_adapter *adapter, int addr, int kind,
                             int (*found_proc)(struct i2c_adapter *, int, int));
```

Debug output:

```
# Uncrustify_d-0.73.0-99-cbf8d8d4
sp_after_tparen_close           = add
# option(s) with 'not default' value: 1
#
# -=====-
# number of loops               = 0
# -=====-
# language                      = C-Header
# -=====-
# Line                Tag         Parent_type  Type of the parent         Columns Br/Lvl/pp      Flag   Nl  Text
#   1>               TYPE|           FUNC_VAR|     PARENT_NOT_SET[  1/  1/  4/  0][0/0/0][      c0000][0-0] int
#   1>        TPAREN_OPEN|           FUNC_VAR|     PARENT_NOT_SET[  5/  5/  6/  1][0/0/0][  203000000][0-0]     (
#   1>           PTR_TYPE|               NONE|     PARENT_NOT_SET[  6/  6/  7/  0][0/1/0][  200080000][0-0]      *
#   1>           FUNC_VAR|               NONE|     PARENT_NOT_SET[  7/  7/ 17/  0][0/1/0][    3080000][0-0]       found_proc
#   1>       TPAREN_CLOSE|           FUNC_VAR|     PARENT_NOT_SET[ 17/ 17/ 18/  0][0/0/0][  200000000][0-0]                 )
#   1>        FPAREN_OPEN|         FUNC_PROTO|     PARENT_NOT_SET[ 19/ 18/ 19/  0][0/0/0][  200000000][0-0]                   (
#   1>             STRUCT|               NONE|     PARENT_NOT_SET[ 20/ 19/ 25/  0][0/1/0][      a0000][0-0]                    struct
#   1>               TYPE|             STRUCT|     PARENT_NOT_SET[ 27/ 26/ 37/  1][0/1/0][     800000][0-0]                           i2c_adapter
#   1>           PTR_TYPE|             STRUCT|     PARENT_NOT_SET[ 39/ 38/ 39/  1][0/1/0][  200000000][0-0]                                       *
#   1>              COMMA|               NONE|     PARENT_NOT_SET[ 40/ 39/ 40/  0][0/1/0][  200000000][0-0]                                        ,
#   1>               WORD|               NONE|     PARENT_NOT_SET[ 42/ 41/ 44/  1][0/1/0][    3080000][0-0]                                          int
#   1>              COMMA|               NONE|     PARENT_NOT_SET[ 45/ 44/ 45/  0][0/1/0][  200000000][0-0]                                             ,
#   1>               WORD|               NONE|     PARENT_NOT_SET[ 47/ 46/ 49/  1][0/1/0][    1080000][0-0]                                               int
#   1>       FPAREN_CLOSE|         FUNC_PROTO|     PARENT_NOT_SET[ 50/ 49/ 50/  0][0/0/0][  200000000][0-0]                                                  )
#   1>          SEMICOLON|           FUNC_VAR|     PARENT_NOT_SET[ 51/ 50/ 51/  0][0/0/0][  200000000][0-0]                                                   ;
#   1>            NEWLINE|               NONE|     PARENT_NOT_SET[ 52/ 51/  1/  0][0/0/0][          0][2-0]
#   3>          QUALIFIER|               NONE|     PARENT_NOT_SET[  1/  1/  7/  0][0/0/0][      e0000][0-0] static
#   3>               TYPE|               NONE|     PARENT_NOT_SET[  8/  8/ 11/  1][0/0/0][      20000][0-0]        int
#   3>      FUNC_CTOR_VAR|               NONE|     PARENT_NOT_SET[ 12/ 12/ 29/  1][0/0/0][    3000000][0-0]            i2c_probe_address
#   3>        FPAREN_OPEN|      FUNC_CTOR_VAR|     PARENT_NOT_SET[ 29/ 29/ 30/  0][0/0/0][  200000000][0-0]                             (
#   3>             STRUCT|               NONE|     PARENT_NOT_SET[ 30/ 30/ 36/  0][0/1/0][400000a0000][0-0]                              struct
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 37/ 37/ 48/  1][0/1/0][40000000000][0-0]                                     i2c_adapter
#   3>           PTR_TYPE|               NONE|     PARENT_NOT_SET[ 49/ 49/ 50/  1][0/1/0][40200000000][0-0]                                                 *
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 50/ 50/ 57/  0][0/1/0][40000000000][0-0]                                                  adapter
#   3>              COMMA|               NONE|     PARENT_NOT_SET[ 57/ 57/ 58/  0][0/1/0][40200000000][0-0]                                                         ,
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 59/ 59/ 62/  1][0/1/0][400000a0000][0-0]                                                           int
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 63/ 63/ 67/  1][0/1/0][40000000000][0-0]                                                               addr
#   3>              COMMA|               NONE|     PARENT_NOT_SET[ 67/ 67/ 68/  0][0/1/0][40200000000][0-0]                                                                   ,
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 69/ 69/ 72/  1][0/1/0][400000a0000][0-0]                                                                     int
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 73/ 73/ 77/  1][0/1/0][40000000000][0-0]                                                                         kind
#   3>              COMMA|               NONE|     PARENT_NOT_SET[ 77/ 77/ 78/  0][0/1/0][40200000000][0-0]                                                                             ,
#   3>            NEWLINE|               NONE|     PARENT_NOT_SET[ 78/ 78/ 30/  0][0/1/0][40000000000][1-0]
#   4>    MACRO_FUNC_CALL|               NONE|     PARENT_NOT_SET[ 30/ 30/ 33/  0][0/1/0][40000080000][0-0]                              int
#   4>        FPAREN_OPEN|    MACRO_FUNC_CALL|     PARENT_NOT_SET[ 34/ 34/ 35/  1][0/1/0][40200000000][0-0]                                  (
#   4>              DEREF|               NONE|     PARENT_NOT_SET[ 35/ 35/ 36/  0][0/2/0][40200080000][0-0]                                   *
#   4>               WORD|               NONE|     PARENT_NOT_SET[ 36/ 36/ 46/  0][0/2/0][40000080000][0-0]                                    found_proc
#   4>       FPAREN_CLOSE|    MACRO_FUNC_CALL|     PARENT_NOT_SET[ 46/ 46/ 47/  0][0/1/0][40200000000][0-0]                                              )
#   4>        FPAREN_OPEN|          FUNC_CALL|     PARENT_NOT_SET[ 47/ 47/ 48/  0][0/1/0][40200000000][0-0]                                               (
#   4>             STRUCT|               NONE|     PARENT_NOT_SET[ 48/ 48/ 54/  0][0/2/0][400000a0000][0-0]                                                struct
#   4>               WORD|               NONE|     PARENT_NOT_SET[ 55/ 55/ 66/  1][0/2/0][40000000000][0-0]                                                       i2c_adapter
#   4>           PTR_TYPE|               NONE|     PARENT_NOT_SET[ 67/ 67/ 68/  1][0/2/0][40200000000][0-0]                                                                   *
#   4>              COMMA|               NONE|     PARENT_NOT_SET[ 68/ 68/ 69/  0][0/2/0][40200000000][0-0]                                                                    ,
#   4>               WORD|               NONE|     PARENT_NOT_SET[ 70/ 70/ 73/  1][0/2/0][40000080000][0-0]                                                                      int
#   4>              COMMA|               NONE|     PARENT_NOT_SET[ 73/ 73/ 74/  0][0/2/0][40200000000][0-0]                                                                         ,
#   4>               WORD|               NONE|     PARENT_NOT_SET[ 75/ 75/ 78/  1][0/2/0][40000080000][0-0]                                                                           int
#   4>       FPAREN_CLOSE|          FUNC_CALL|     PARENT_NOT_SET[ 78/ 78/ 79/  0][0/1/0][40200000000][0-0]                                                                              )
#   4>       FPAREN_CLOSE|      FUNC_CTOR_VAR|     PARENT_NOT_SET[ 79/ 79/ 80/  0][0/0/0][40200000000][0-0]                                                                               )
#   4>          SEMICOLON|      FUNC_CTOR_VAR|     PARENT_NOT_SET[ 80/ 80/ 81/  0][0/0/0][  200000000][0-0]                                                                                ;
#   4>            NEWLINE|               NONE|     PARENT_NOT_SET[ 81/ 81/  1/  0][0/0/0][          0][1-0]
# -=====-
```

Note that ordinarily, the first `)` in the function pointer is correctly detected as a `TPAREN_CLOSE`, but if the function pointer is itself a function argument, it is detected as an `FPAREN_CLOSE`.

### PR DESCRIPTION
**Pull request by guy-maurel**
is corrected
fixes #3259

### CODE REVIEW

**Comment by alexhenrie** [comment]
This is an improvement, but it doesn't fix the problem completely. For example, `sp_after_tparen_close=add` transforms this input:

```c
static int i2c_probe_address(struct i2c_adapter *adapter, int addr, int kind,
			     int (*found_proc1)(struct i2c_adapter *, int, int),
			     int (*found_proc2)(struct i2c_adapter *, int, int));
```

Into this output:

```c
static int i2c_probe_address(struct i2c_adapter *adapter, int addr, int kind,
			     int (*found_proc1)(struct i2c_adapter *, int, int),
			     int (*found_proc2) (struct i2c_adapter *, int, int));
```

A space should be added after both `(*found_proc1)` and `(*found_proc2)`, but it is only added to the first one.

**Comment by alexhenrie** [comment]
Thanks for fixing it! We should probably also update the test to have two function pointer arguments, like in my comment above.

**Comment by guy-maurel** [comment]
we have stil a problem with the test c:00420

**Review by gmaurel — CHANGES_REQUESTED** [review]
is not ready to be merge,
see test c:00420

**Comment by guy-maurel** [comment]
I need a break.

**Comment by guy-maurel** [comment]
will be solved later

**Pull request closed without merging**
