### PR TITLE
resolve the wrong type for bar & mask

### LINKED ISSUE #3558: Bitwise AND incorrectly identified as reference variable in ternary expression
Config file:

```
sp_before_byref = remove
```

Original code:

```
int main()
{
	return foo ? foo : bar & mask;
}
```

Expected output: No change

Actual output:

```
int main()
{
	return foo ? foo : bar& mask;
}
```

Parse output:

```
# Uncrustify_d-0.74.0_f
# option(s) with 'not default' value: 0
#
# -=====-
# number of loops               = 0
# -=====-
# language                      = CPP
# -=====-
# Line                Tag         Parent_type  Type of the parent         Columns Br/Lvl/pp      Flag   Nl  Text
#   1>               TYPE|           FUNC_DEF|     PARENT_NOT_SET[  1/  1/  4/  0][0/0/0][      e0000][0-0] int
#   1>           FUNC_DEF|               NONE|     PARENT_NOT_SET[  5/  5/  9/  1][0/0/0][          0][0-0]     main
#   1>        FPAREN_OPEN|           FUNC_DEF|     PARENT_NOT_SET[  9/  9/ 10/  0][0/0/0][  200000000][0-0]         (
#   1>       FPAREN_CLOSE|           FUNC_DEF|     PARENT_NOT_SET[ 10/ 10/ 11/  0][0/0/0][  200000008][0-0]          )
#   1>            NEWLINE|               NONE|     PARENT_NOT_SET[ 11/ 11/  1/  0][0/0/0][          0][1-0]
#   2>         BRACE_OPEN|           FUNC_DEF|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][  200000000][0-0] {
#   2>            NEWLINE|               NONE|     PARENT_NOT_SET[  2/  2/  9/  0][1/1/0][          0][1-0]
#   3>             RETURN|               NONE|     PARENT_NOT_SET[  9/  9/ 15/  0][1/1/0][      e0000][0-1]         return
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 16/ 16/ 19/  1][1/1/0][      80000][0-0]                foo
#   3>           QUESTION|               NONE|     PARENT_NOT_SET[ 20/ 20/ 21/  1][1/1/0][  200000000][0-0]                    ?
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 22/ 22/ 25/  1][1/1/0][      80000][0-0]                      foo
#   3>         COND_COLON|               NONE|     PARENT_NOT_SET[ 26/ 26/ 27/  1][1/1/0][  200000000][0-0]                          :
#   3>               TYPE|               NONE|     PARENT_NOT_SET[ 28/ 28/ 31/  1][1/1/0][     8c0000][0-0]                            bar
#   3>              BYREF|               NONE|     PARENT_NOT_SET[ 32/ 32/ 33/  1][1/1/0][  200800000][0-0]                                &
#   3>               WORD|               NONE|     PARENT_NOT_SET[ 34/ 34/ 38/  1][1/1/0][    3000000][0-0]                                  mask
#   3>          SEMICOLON|               NONE|     PARENT_NOT_SET[ 38/ 38/ 39/  0][1/1/0][  200000000][0-0]                                      ;
#   3>            NEWLINE|               NONE|     PARENT_NOT_SET[ 39/ 39/  1/  0][1/1/0][          0][1-0]
#   4>        BRACE_CLOSE|           FUNC_DEF|     PARENT_NOT_SET[  1/  1/  2/  0][0/0/0][  200000000][0-0] }
#   4>            NEWLINE|               NONE|     PARENT_NOT_SET[  2/  2/  1/  0][0/0/0][          0][1-0]
# -=====-
```

### PR DESCRIPTION
**Pull request by guy-maurel**
Fixes #3558

### CODE REVIEW

**Comment by alexhenrie** [comment]
I would amend the commit to say "resolve" rather than "revolve", like you already did in the pull request ;-) But the code looks good to me. Thank you!

**Comment by micheleCTDE** [comment]
@guy-maurel do you need a big test to check for possible regression?

**Comment by guy-maurel** [comment]
Yes, a bigger test would be welcome as the PR is very complicated.
Thanks for any comment!

**Comment by micheleCTDE** [comment]
> Yes, a bigger test would be welcome as the PR is very complicated. Thanks for any comment!

Looks good, no regressions in my usual big test.

**Comment by guy-maurel** [comment]
Thanks for the big test!

**Review by gmaurel — APPROVED** [review]

**Comment by micheleCTDE** [comment]
> Looks good, no regressions in my usual big test.

I have to take this back. I must have messed up during the testing somehow.
I see two regressions with my config and my test repo:
1) in some cases  a multiplication * is attached to the previous chunk instead of being separated
2) in 2 cases the brace have not been added around the body of a case inside a switch.

I have to say that out of 3200 test files I have add only few regression (less than 10 files), but nevertheless they are regression. I can publish the files in question if needed.

@guy-maurel
How should be proceed from here? Revert, fix, merge again? or just make a fix without revert? The regressions are not major and I don't have urgency to get them fix, so I am ok with both approaches.

Sorry for the wrong reporting before...

**Comment by gmaurel** [comment]
Please, create a/some new issue(s)

**Comment by micheleCTDE** [comment]
Ok, I will create issue during the weekend, I need to recreate the files.

**Pull request merged**
