### PR TITLE
Fix underflow

### PR DESCRIPTION
**Pull request by CDanU**
ref: #1111

### CODE REVIEW

**Comment by stefan-nu** [comment]
Hi @CDanU,

in File indent line 312 you have changed
`size_t col_delta = column - pc->column;`
to
`auto col_delta = static_cast<int>(column) - static_cast<int>(pc->column);`

Shouldn't the same code on line 233 be changed as well?
`size_t col_delta = column - pc->column;`

**Comment by CDanU** [comment]
Yes, good catch, I will make a PR.

**Comment by stefan-nu** [comment]
You have changed the option "align_right_cmt_gap" From `AT_NUM` to `AT_UNUM`.

Shouldn't the configuration files be changed accordingly?
In test/config/ger.cfg line 192: 
`align_right_cmt_gap                      = -5`
Should probably become 
`align_right_cmt_gap                      = 0`

**Comment by guy-maurel** [comment]
The option is no more present.

**Pull request merged**
