### PR TITLE
uncrustify needs some more documentations.

### PR DESCRIPTION
**Pull request by gmaurel**
Let me know if it is the right way to help the beginners

### CODE REVIEW

**Comment by CDanU** [comment]
The current style is a bit plain, maybe [sphinx](http://www.sphinx-doc.org/en/1.5.1/) could be used for this? 
A bad example for this is CMake, a fairly good on is [OpenCV](http://docs.opencv.org/2.4/doc/tutorials/imgproc/imgtrans/hough_lines/hough_lines.html)

In the webtool that I made (which development currently is on hold) I wanted to create for every option an example. The real complexity lies within combining options and document such issues as #852.

I see that you have examples in there for combined options, maybe we should collect [public uncrustify configs](https://encrypted.google.com/search?hl=en&q=site%3Agithub.com%20uncrustify.cfg) and see what people are using/not using to get a feeling what should maybe be documented?

**Comment by mihaipopescu** [comment]
Why HTML when Markdown is so much simpler ?

**Comment by gmaurel** [comment]
@CDanU OK, I wait for your tool.

**Comment by CDanU** [comment]
Which one of the tools do you mean? Anyway don't wait up on me or my tools.

As @mihaipopescu mentioned markdown would be easier to start with and Github does have a wiki system with markdown support. We can set up some HTML docs or a website later if markdown is too restrictive.

**Pull request merged**
