### PR TITLE
Code improvements/search

### PR DESCRIPTION
**Pull request by micheleCTDE**
1. Replace chunk_search() with Chunk::Search()
2. Rename some enum and typedef (please advise if different naming is preferred, like for example EScore and TSearchFnPtr)
3. Camel case all Chunk members
4. Make existing Chunk::GetNext* and Chunk::GetPrev* members const

### CODE REVIEW

**Review by gmaurel — APPROVED** [review]
Fine next step

**Review by gmaurel — CHANGES_REQUESTED** [review]
some conflicts

**Comment by micheleCTDE** [comment]
> sorry for the conflict.

No worries, cheap git rebase operation and a bit of editing and all is sorted.
Rebased on top of latest uncrustify/master.

**Review by gmaurel — APPROVED** [review]

**Comment by alexhenrie** [comment]
The new code crashes, see #3538 :-(

**Pull request merged**
