### PR TITLE
Avoid referencing possibly nonexistent elements in backup_copy_file

### LINKED ISSUE #3310: `uncrustify --replace` crashes on empty file when compiled with -D_GLIBCXX_ASSERTIONS
`-D_GLIBCXX_ASSERTIONS` is set by default on Arch Linux, which results in the following crash (test.cfg and test.c are files of size 0):

```
$ gdb uncrustify
GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from uncrustify...
(No debugging symbols found in uncrustify)
(gdb) run --replace -c empty.cfg empty.c
Starting program: /usr/bin/uncrustify --replace -c empty.cfg empty.c
Parsing: empty.c as language C
/usr/include/c++/11.1.0/bits/stl_vector.h:1063: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) const [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>; std::vector<_Tp, _Alloc>::const_reference = const unsigned char&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7bd5d22 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7bd5d22 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7bbf862 in abort () from /usr/lib/libc.so.6
#2  0x00005555555b794f in backup_copy_file(char const*, std::vector<unsigned char, std::allocator<unsigned char> > const&)
    ()
#3  0x0000555555665eba in ?? ()
#4  0x0000555555597eeb in main ()
```

### PR DESCRIPTION
**Pull request by alexhenrie**
Fixes #3310

### CODE REVIEW

**Review by gmaurel — CHANGES_REQUESTED** [review]
Make a change at line 101

**Comment by alexhenrie** [comment]
Done

**Review by gmaurel — APPROVED** [review]

**Review by gmaurel — APPROVED** [review]
Fine. Thanks to Alex Henrie!

**Comment by alexhenrie** [comment]
Thank you!

**Pull request merged**
