### PR TITLE
Added `--if-changed` to write to stdout/FILE only if a change was detected

### PR DESCRIPTION
**Pull request by mihaipopescu**
New `--if-changed` option that will avoid writing and all related file operations if code was detected not to change. Caller can detect this by testing existence of '.uncrustify' file.

### CODE REVIEW

**Comment by sjakub** [comment]
Does this mean that '.uncrustify' file will not be created if it is no different than the original?
Also, how does that affect the --no-backup behaviour? The help text for the option should clarify that.

**Comment by mihaipopescu** [comment]
The new option should not influence the behaviour of '--no-backup' or '--replace'. Why do you think otherwise ?

**Comment by sjakub** [comment]
I feel like "write to" is confusing in context of files, especially if sometimes new files are not created regardless... I think it should say "create files or write to stdout".

**Comment by gmaurel** [comment]
Well!
Merge or not merge?

**Comment by sjakub** [comment]
Thanks! :)

**Comment by mihaipopescu** [comment]
Thank you too for being watchful ! @gmaurel I think we're good to go if you don't have any other objections.

**Pull request merged**
