### PR TITLE
add support for C11 char literal prefixes

### PR DESCRIPTION
**Pull request by CDanU**
ref: #945

### CODE REVIEW

**Comment by gmaurel** [comment]
@CDanU I might have make an error as I resolve the conflict.

**Comment by CDanU** [comment]
I'll fix it ... let me handle that for my commits, I am willing to rebase those myself.

**Comment by gmaurel** [comment]
Sorry for the trouble.

**Comment by CDanU** [comment]
Nahh, merge conflicts are normal, nothing to be sorry for. 
It is rebased it now, I would like you to try to include it via [githubs own rebase functionallity](https://github.com/blog/2243-rebase-and-merge-pull-requests) instead of a normal merge this time.

**Pull request merged**
