### PR TITLE
Simplify the CI workflow file by using matrix.

### PR DESCRIPTION
**Pull request by dundargoc**
Also bump action version to 3.

### CODE REVIEW

**Review by micheleCTDE — APPROVED** [review]
Hi @dundargoc,
this looks good to me. Nevertheless I will wait for @gmaurel to also approve before merging it. He is on leave for this week, so this PR will be pending a few days.

**Review by gmaurel — APPROVED** [review]
fine

**Comment by micheleCTDEAdmin** [comment]
Reopened in order to merge.

**Comment by micheleCTDEAdmin** [comment]
Will merge when the automatic checks have passed (again).

**Comment by micheleCTDEAdmin** [comment]
finally merged :-)

**Pull request merged**
