### PR TITLE
introduce a new option for the comments such as

### LINKED ISSUE #3614: [Feature Request] comment ignore regex
The linter I use requires that lint instruction comments follow the following syntax:
`//lint {...}`, but my uncrustify config adds a space at the beginning of comments, so it will become: `// lint {...}`.

Request here is to add a "comment ignore regex" which would allow uncrustify to skip formatting any comment that matches the regex. Clang-format has this functionality, called CommentPragmas (see docs [here](https://clang.llvm.org/docs/ClangFormatStyleOptions.html))

### PR DESCRIPTION
**Pull request by guy-maurel**
//lint
to remove the space before **lint**
fixes #3614

### CODE REVIEW

**Comment by rickyelopez** [comment]
Tested this, works for me! Thank you!

**Comment by gmaurel** [comment]
You wrote:
`Bump on this @gmaurel `
What is the meaning of _Bump_ ?

**Comment by rickyelopez** [comment]
Bump means a comment that does not add any information but serves to remind people that something exists. I had not commented on the ticket for a long time, so I assumed that it was no longer on your mind.

**Review by micheleCTDEAdmin — APPROVED** [review]
Looks good

**Pull request merged**
