### PR TITLE
Unify the use of static_inline as static inline

### PR DESCRIPTION
**Pull request by guy-maurel**
over all the sources

### CODE REVIEW

**Comment by mwoehlke** [comment]
Looks okay, I guess, but why do we need this macro in the first place? I'd as soon see us get rid of it...

**Comment by guy-maurel** [comment]
It was introduced by Ben on Wed Apr 15 04:31:59 2009.
If it is good, let us use it overall,
if it is wrong, let us supress it overall.
Other opinions?

**Comment by guy-maurel** [comment]
Thanks for the tip. I incline to removal also.

**Comment by arneforlie** [comment]
In the first commit you added #include "base_types.h" in order to be able to use the macro.
But you forgot to remove the #include again when reverting the change in the second commit.

That said, I do not understand the reason for static inline, and I think is this is a remnant of the code being C originally.
The way to do this in C++ is with inline on its own.
When you use static inline I suspect that each TU gets its own copy in those cases where the compiler decides that it doesn't want to inline the function. With just inline the linker should collapse all out-of-line instances into one, giving a smaller executable.

**Comment by mwoehlke-kitware** [comment]
> The way to do this in C++ is with inline on its own. When you use static inline I suspect that each TU gets its own copy in those cases where the compiler decides that it doesn't want to inline the function.

`static` is used to specify internal linkage, so I suspect you are correct for those instances (most of them) where this pattern appears in a header. (In `.cpp`s, it would be preferable to use anonymous namespaces instead, especially since — as of C++11 — functions in anonymous namespaces implicitly have internal linkage.) Actually, I think this would have been the case even with C89, i.e. stuff in headers should *never* be internal linkage.

(Note: Even though `inline` is basically meaningless these days from an optimization standpoint, I believe `inline` in headers is still useful (even necessary) to avoid violating the [ODR](https://en.wikipedia.org/wiki/One_Definition_Rule).)

**Pull request merged**
