### PR TITLE
recalculate the level after #endif

### LINKED ISSUE #3336: Wrong variable indentation when using for loop block + #ifndef + label
When I am using for loop block + #ifndef + label,  the alignment of variable removed
file with C code example attached + configuration (just remove .txt extension)

[uncrustify.cfg.txt](https://github.com/uncrustify/uncrustify/files/7278356/uncrustify.cfg.txt)
[test.c.txt](https://github.com/uncrustify/uncrustify/files/7278348/test.c.txt)

### PR DESCRIPTION
**Pull request by guy-maurel**
fixes #3336

### CODE REVIEW

**Comment by guy-maurel** [comment]
@micheleCTDE Could you please make your big test?

**Comment by micheleCTDE** [comment]
Hi Guy,
I see several regressions when tested on my usual test repo. Things like 
1. wrong indentation of continuation lines when a line is too long
2. open braces joined to original line even when my setup is fully Allman
3. spaces used instead of tabs when indenting
4. more files where uncrustify abort with errors instead of completing its tasks.

There could be even more perhaps.

You can access the test files at the locations below:
- [this](https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest/src/branch/test-PR-3384) is the result of uncrustify with PR 3384 applied
- [this](https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest/src/branch/v25-45224115) is the result of uncrustify/master. Make sure to checkout commit 3d776d4968 for a direct single pass to single pass comparison.

If you compare the two folders, you will see several differences. Look at [this file](https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest/src/branch/test-PR-3384/format_errors1.log) for errors on abort execution (if you compare the two branches, those are clear) and pick pretty much any file that differs to see some examples of the differences.
The config file used was the same in both cases and you can find it [here](https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest/src/branch/test-PR-3384/.uncrustify_tde.cfg)

**Comment by micheleCTDE** [comment]
We should **not** merge this PR as is.

**Comment by micheleCTDE** [comment]
Forgot to add that you can access the original non-uncrustified files [here](https://mirror.git.trinitydesktop.org/gitea/MicheleC/styleTest/src/branch/master), if you want to run a test locally.

**Review by gmaurel — CHANGES_REQUESTED** [review]
@micheleCTDE has too much errors

**Comment by micheleCTDE** [comment]
> @micheleCTDE has too much errors

Indeed, way too many. Definitely need some rework. Let me know when you need a new test and I will run again.

**Comment by gmaurel** [comment]
replaced by #4339

**Pull request closed without merging**
