### PR TITLE
Introducing align_var_class_span and friends

### PR DESCRIPTION
**Pull request by dzenanz**
#648 Adding align_var_class_span, align_var_class_thresh and align_var_class_gap
to have separate control over class member declaration alignment.

### CODE REVIEW

**Comment by mihaipopescu** [comment]
While updating a test can you also add new tests for the new options ?

**Comment by dzenanz** [comment]
This is ready to be merged.

**Comment by gmaurel** [comment]
Not in this way, please.
Do not change the "ben.cfg"
As it is necessary, create a new configuration file to be used for your changes.

**Comment by dzenanz** [comment]
Either ben.cfg needs to be changed, or the expected output of a few tests which use it. The third commit adds a test for the new functionality.

**Comment by mihaipopescu** [comment]
@gmaurel If we change ben.cfg then we have to change all references. For what the old ben.cfg is useful ? I've already seen one in `etc` folder. I think we can make a backup of it if that's what you want (even if we can always get back from git history).

**Pull request merged**
