### PR TITLE
Fix missing documentation for some options

### PR DESCRIPTION
**Pull request by micheleCTDE**
Some options were added without properly updating all required files. This PR fixes that.

@guy-maurel: will wait for you approval before merging.

### CODE REVIEW

**Review by gmaurel — COMMENTED** [review]
etc/uigui_uncrustify.ini:
I think, the build of these file should be done with a release version to avoid the (numbers)
The (numbers) are more for debugging cases

**Comment by micheleCTDEAdmin** [comment]
> etc/uigui_uncrustify.ini: I think, the build of these file should be done with a release version to avoid the (numbers) The (numbers) are more for debugging cases

I agree. The only reason I kept the numbers is that they were already present in the current master code. I also think we should not have the numbers there.
I will update the PR tomorrow and remove the numbers, then I will post the new version.

**Comment by micheleCTDE** [comment]
PR updated removing the option numbering.

**Comment by micheleCTDE** [comment]
@gmaurel let me know if ok now

**Review by gmaurel — APPROVED** [review]
Fine, Thanks

**Pull request merged**
