### PR TITLE
Fix 1683 - Don't put newline after brace close in @ OC declarations

### PR DESCRIPTION
**Pull request by Krizai**
Fix for https://github.com/uncrustify/uncrustify/issues/1683

I don't think we ever need to put a newline after closing brace in @{} OC dictionary declarations

### CODE REVIEW

**Comment by guy-maurel** [comment]
Don't miss to use:
```
cd <uncrustify_dir>/tests/cli
./test_cli_options.py
```
to prevent the errror(s)

**Comment by Krizai** [comment]
I tried. It's strange, but on my machine, it passed without any errors.

**Comment by gmaurel** [comment]
Please, have a look to: https://travis-ci.org/uncrustify/uncrustify/jobs/355555824
Push more details about "your machine"

**Comment by guy-maurel** [comment]
You need some more verbosity.
Change the file` .travis.ym`l, line 91from:
`  - if [ "x${BUILD_TYPE}" == "xrelease" ]; then cd ../tests/cli && ./test_cli_options.py; cd -; fi`
to
`  - if [ "x${BUILD_TYPE}" == "xrelease" ]; then cd ../tests/cli && ./test_cli_options.py --diff; cd -; fi`
to get _"show diffs when there is a test mismatch"_

**Pull request merged**
