### PR TITLE
Fix for issue #3116 [C++] lambdas are not aligned within compound statements

### PR DESCRIPTION
**Pull request by CharlieYJH**
This is my proposed fix for https://github.com/uncrustify/uncrustify/issues/3116. It fixes the cases raised in the issue and tries to fix other common cases as well.

### CODE REVIEW

**Review by gmaurel — APPROVED** [review]
Thank for the PR

**Comment by mwoehlke** [comment]
So... this caused a regression:
```c++
// What you want
const auto compare = [] (const auto i, const auto j)
{
    return i >= j;
};

// What neither of us wants
const auto compare = [] (const auto i, const auto j)
    {
        return i >= j;
    };

// What I want and used to get
const auto compare = [] (const auto i, const auto j)
                     {
                         return i >= j;
                     };

// But now it is this which nobody wants
const auto compare = [] (const auto i, const auto j)
                 {
                     return i >= j;
                 };
```

**Comment by CharlieYJH** [comment]
Could you share your config?

**Comment by mwoehlke** [comment]
> Could you share your config?

https://github.com/Kitware/kwiver/blob/master/.uncrustify.cfg

**Comment by mwoehlke** [comment]
...and here's a test case:
```c++
void func()
{
  auto deleter = []( void* ptr )
                 {
                   free( ptr );
                 };
}
```

Prior to this PR, the above was unchanged. With this PR, it is malformatted.

**Comment by CharlieYJH** [comment]
Opened a PR at https://github.com/uncrustify/uncrustify/pull/3200 which tries to fix this regression.

**Pull request merged**
