### PR TITLE
cmake: use GNU install paths based on compiler

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by CDanU** [comment]
What happens when you use non msvc compilers on windows like mingw?

**Comment by Biswa96** [comment]
Added.

**Comment by guy-maurel** [comment]
@CDanU what do you think about?

**Comment by mwoehlke-kitware** [comment]
> [Description] added.

Added _where_? Am I missing something?

I guess this means that on msys/mingw, things will now get installed into e.g. `<prefix>/bin/uncrustify` instead of `<prefix>/uncrustify`. Given that those are meant to be *nix-like, that doesn't seem unreasonable. (On Windows, especially for something like uncrustify that is not many files, it is typical to not have a hierarchy under the prefix, especially as the prefix might be something like `C:\Program Files\MyApplication`; hence the MSVC behavior.)

**Comment by Biswa96** [comment]
Added in the commit message. Yes, that logic.

**Comment by gmaurel** [comment]
@mwoehlke-kitware  and now, what do you think about?

**Review by mwoehlke-kitware — APPROVED** [review]

**Comment by mwoehlke-kitware** [comment]
(For the record, on 2020-10-06, I stated that this "doesn't seem unreasonable" :slightly_smiling_face:)

**Review by gmaurel — APPROVED** [review]

**Pull request merged**
