### PR TITLE
Add CLI option to dump formatting steps

### PR DESCRIPTION
**Pull request by micheleCTDE**
Add ability to dump the parsing information at different steps of the formatting process. See documentation in the code for more details. 
Useful for debugging complicated issues.

### CODE REVIEW

**Comment by micheleCTDE** [comment]
If you think there are more points where dumping would be useful, feel free to suggest the location.

**Comment by guy-maurel** [comment]
Please, resolve the conflict.

**Comment by guy-maurel** [comment]
Please, put one/many files to explains how it works, such as `_documentation/track.html_`,
not only in the code.

**Comment by guy-maurel** [comment]
`_more points where dumping would be useful, feel free to suggest the location_`
Well, I am not a friend of having any dump with the _release option_.
I would prefer to have a conditional compiling.
Each developer could add the line of code at other places, because it is not predictable to
say today, where is a good location.

Please, introduce a bigger description with a simple example.

This is similar to _prot_the_line(__func__, __LINE__, pc->orig_line);_

It might be usefull to add your proposal at `src/unc_tools.cpp`

**Comment by micheleCTDE** [comment]
Hi Guy,
thanks for the feedback. Here is additional info for you.

> Please, resolve the conflict.
Done, this was caused by another PR modifying README.md as well

> Please, put one/many files to explains how it works, such as _documentation/track.html_, not only in the code.
I have attached a zip file with an example of what the output looks like. It was generated by running:
```
uncrustify -c test.cfg -f in.cpp -o out.cpp -p parsing.p -L A 2>log.A -ds dump
```
You are already familiar with 'p' and 'A' files. The additional dump files contain the parsing sequence at different steps of the formatting process (basically they are 'p' files at different moment in time). It can be useful to understand when something is changed and where to focus in the code.

> Well, I am not a friend of having any dump with the release option. I would prefer to have a conditional compiling.
I would say that the information in the generated dumps is no different from that contained in the 'p' file and therefore in my opinion the -ds options should belong into a release as well (in fact I think it would help users to find their problems more easily). In any case you are the maintainer, so if in the end you prefer to have a conditional compiling option, I will adjust the code for that. Perhaps you may want to discuss among the other core devs first and then let me know you final opinion on this.

[example.zip](https://github.com/uncrustify/uncrustify/files/6986768/example.zip)

**Comment by micheleCTDE** [comment]
Sorry, forgot to add that README.md and the man file already have an explanation of what the command line '-ds' option do.
```
-ds FILE
Dump parsing info at various moments of the formatting process.
This creates a series of files named 'FILE_nnn.log', each
corresponding to a formatting step in uncrustify.
The file 'FILE_000.log' lists the formatting options in use.
Must be used in combination with '-f FILE'
```

**Comment by micheleCTDE** [comment]
> Please, put one/many files to explains how it works, such as documentation/track.html, not only in the code.

Now I get what you meant! I will add some documentation there tomorrow and update the PR :+1:

**Comment by micheleCTDE** [comment]
Hi Guy,
I have added the file 'documentation/dump-steps.txt' where I have described the purpose of the command line option and its generated output.

Please review and let me know what you think about it. Also let me know if the PR is now fine as is or if you still want to have conditional compiling flag for this.

**Review by gmaurel — APPROVED** [review]
fine

**Comment by micheleCTDE** [comment]
ok, great. Thanks for the feedback throughout.

**Pull request merged**
