### PR TITLE
Update Travis script

### PR DESCRIPTION
**Pull request by jibsen**
I am playing around with the Travis script a bit, so atm this PR is just to get build status info.

### CODE REVIEW

**Comment by jibsen** [comment]
Okay, seems to be working now. This adds a Win64 cross-compile using mingw-w64 to Travis.

I also switched to Clang for the address sanitizer build, and moved the package installs to the build matrix (only install the packages required for each build).

**Comment by mihaipopescu** [comment]
@jibsen Awesome. Thanks for checking this out ! It's really important to have the biggest coverage we can have.

Actually I was thinking about this as I've seen you've also added a Coverage build type but it's still inactive. I think we can really make http://coveralls.io to work with CMake and then put a coverage badge on the first page.

I saw that CMake already has support for Coverage so I started writing a few things.

```cmake
if(BUILD_TESTING)
  enable_testing()
  add_subdirectory(tests)

  if(ENABLE_COVERAGE)
    include(CodeCoverage)
    # debug, no optimisation, enable coverage
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -O0 -fprofile-arcs -ftest-coverage")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fprofile-arcs -ftest-coverage")
    SETUP_TARGET_FOR_COVERAGE(uncrustify_coverage "ctest" "_coverage")
    target_link_libraries(uncrustify gcov)
  endif()

endif()
```

**Comment by gmaurel** [comment]
Some more comments before I merge?

**Comment by jibsen** [comment]
@mihaipopescu, I think adding coverage would be a good idea. But perhaps it would be better if you start a new PR for working on that.

**Comment by mihaipopescu** [comment]
@gmaurel Looks good to me.
@jibsen Yeah. First I need to have something working.

**Pull request merged**
