### PR TITLE
add AppVeyor badge

### PR DESCRIPTION
**Pull request by dirk-thomas**
Please do **not** merge this until the AppVeyor project has been created, this PR has been tested by AppVeyor, and the badge actually shows the build result. See #538 on how to setup the project and retrigger the CI for this PR once that has happened.

### CODE REVIEW

**Comment by mihaipopescu** [comment]
@dirk-thomas We have to update the link for appveyor because from what I'm seeing we have an uncrustify project linked on AppVeyor probably created by @bengardner for the old project link but I think it doesn't matter as long as it's actually linked with this one. 

Can you update the change with this link https://ci.appveyor.com/project/bengardner/uncrustify/ ?

**Comment by dirk-thomas** [comment]
If there is any chance to get @bengardner to update the AppVeyor project and create one for `uncrustify/uncrustify` I would very much prefer that. From the used URL it is completely unclear that the AppVeyor project is actually checking this repo rather then his fork (https://github.com/bengardner/uncrustify).

**Comment by mihaipopescu** [comment]
Sure, that would be ideal. pinging also @gmaurel.

**Comment by bengardner** [comment]
I changed the group name on appveyor to uncrustify.  We'll see if that did
what we want.

**Comment by dirk-thomas** [comment]
Looks good to me: https://github.com/dirk-thomas/uncrustify/blob/31b21e2c7aaf36842a99b59ceb86bdd41d4337c1/README.md

**Comment by dirk-thomas** [comment]
It looks like you added the badge (without the name of the service) in 78332f381a7dcb9d4d85fc4b4ffd64b53d42fce0. Do you still want this to be merged (adding the names of the services to the badges) then I would rebase or should it be closed?

**Comment by mihaipopescu** [comment]
I think it would be good to have something to avoid confusion between them but I don't think the name of the service is relevant here for the developers. Instead I think we could have something like `Windows build | passing` and `UNIX build | passing`. What do you think ?

**Comment by dirk-thomas** [comment]
I updated it to just "Linux" and "Windows" (https://github.com/dirk-thomas/uncrustify/blob/e033c94a0a7f378f56e2b49145316952cbe3fe99/README.md) since its also running tests after building :wink:

We can update the Travis label when we add e.g. OS X if anyone cares.

**Pull request merged**
