### PR TITLE
Fix lambda indentation in cpp function argument list regression

### LINKED ISSUE #3428: Regression [0.74 -> master] C++: incorrect indentation of lambas in multiline function arguments
[//]: # "  If the issue is connected to existing Uncrustify options please, if possible, add the"
[//]: # "  following information to ease up the process:"
[//]: # "  • a link to a debug file:"
[//]: # "      generated with: 'uncrustify -p debug.txt -c pathToUsedConfig.cfg -f toBeFormatedFile.cpp' "
[//]: # "      Example: [debug.txt](https://linkToTheFile)"
[//]: # "      Example hosters for debug files: pastebin.com, gist.github.com, ..."
[//]: # "      The used config file is included in the debug file and does not need to be included here."
[//]: # 
[//]: # "  • include a small but complete test file that will be uncrustifyed"
[//]: # "  • include the generated results"
[//]: # "  • include the expected results"
[//]: # 
[//]: # "  ✋ please add a line containing ``` above and below of each of those three code sections"
[//]: # 
[//]: # "  • include the current version of your Uncrustify executable"
[//]: # "      printout via 'uncrustify -v'"
[//]: # "      Example: current version: uncrustify 0.63"
[//]: # "      or if possible additionally with the git sha of the commit"
[//]: # "                    current version: uncrustify 0.63 dc7b412"
[//]: # 
[//]: # "  • if possible include a version that worked"
[//]: # "      Example: working version: uncrustify 0.63"
[//]: # "      or"
[//]: # "                    working version: uncrustify 0.63 2a5e88f"

Whoops, sorry. I broke this in #3409.

```
$ ./uncrustify.exe -v
Uncrustify-0.74.0-38-b64d3f7d
```

input
```
void main()
{
	if(aaaa)
			{
				it = std::find_if(
					bbbb.begin(),
					bbbb.end(),
					[&cccc](const auto& dddd)
				{
					return (eeee.ffff == iiii && !jjjj.kkkk);
				}
				);
			}
}
```

config
```
indent_cpp_lambda_body      = true
indent_cpp_lambda_only_once = true

indent_columns = 4
indent_with_tabs = 0
indent_continue = 4
indent_paren_close = 2
```

expected output
```
void main()
{
    if(aaaa)
    {
        it = std::find_if(
            bbbb.begin(),
            bbbb.end(),
            [&cccc](const auto& dddd)
            {
                return (eeee.ffff == iiii && !jjjj.kkkk);
            }
        );
    }
}
```

actual output
```
void main()
{
    if(aaaa)
    {
        it = std::find_if(
            bbbb.begin(),
            bbbb.end(),
            [&cccc](const auto& dddd)
        {
            return (eeee.ffff == iiii && !jjjj.kkkk);
        }
        );
    }
}
```

I've got a fix in the works, but I'm making sure I dont introduce another regression again before I post a merge request. I'm also going to add tests for `indent_cpp_lambda_only_once` as well since that code is part of the reason I introduced this regression.

### PR DESCRIPTION
**Pull request by JodiTheTigger**
Fixes #3428

### CODE REVIEW

**Comment by gmaurel** [comment]
Please have a look to:
https://github.com/JodiTheTigger/uncrustify/actions
and activate the workflow.
So, I could see the results

**Review by gmaurel — CHANGES_REQUESTED** [review]
Please activate the workflow

**Comment by JodiTheTigger** [comment]
Ok, hopefully I have activated the workflow so you can see it

**Comment by guy-maurel** [comment]
But you need to make a little change on the code, to get it/the PR  run again.
Onyly after that, we could see the workflow results.

**Comment by gmaurel** [comment]
@JodiTheTigger : Please have a look to the conflict

**Review by gmaurel — APPROVED** [review]

**Pull request merged**
