### PR TITLE
Make generating token_names.h part of the build

### PR DESCRIPTION
**Pull request by jibsen**
As discussed in #604, `token_names.h` was not being regenerated if the source file changed. This should hopefully fix that.

### CODE REVIEW

**Comment by jibsen** [comment]
Btw, Travis is not using CMake yet, so the build check means nothing for this PR.

**Comment by mihaipopescu** [comment]
Yes. We are waiting for @gmaurel to integrate AppVeyor.

**Comment by mihaipopescu** [comment]
Btw, I've noticed that `token_names.h` is not part of the workspace. It don't think it's required but I wanted to ask if this change also links it's rebuild as a part of the regular build process. For instance, if I'm adding or removing a token from `token_enums.h` and if I do a build does it trigger the regenerate action ?

Now I have to go to command line and run `make_token_names.bat` but I wish it was added as a pre-build event.

**Comment by mihaipopescu** [comment]
Now I have to go to command line and run `make_token_names.bat` and move it from `src` to `build` folder but I wish it was added as a pre-build event.

**Comment by jibsen** [comment]
With this change, it should trigger a rebuild of `token_names.h` (and the files that include it) when building, if you change `token_enums.h`. You can look for the line "Generating token_names.h" in the build log.

**Pull request merged**
