### PR TITLE
Ensure that switch statements inside lambdas are indented correctly

### LINKED ISSUE #3761: indent_switch_case broken inside lambda
Version: `Uncrustify_d-0.75.1_f`

Command: `./build/uncrustify -c tests/config/common/empty.cfg -f indent-case.cpp -p indent-case.txt`

Debug file: [indent-case.txt](https://github.com/uncrustify/uncrustify/files/9169824/indent-case.txt)

Input:
```
namespace ns
{
f([]() {
		switch (x) {
		case 1:
			break;
		}
	});
}
```

Output:
```
namespace ns
{
f([]() {
		switch (x) {
			case 1:
				break;
		}
	});
}
```

Expected:
```
namespace ns
{
f([]() {
		switch (x) {
		case 1:
			break;
		}
	});
}

```

First bad commit: 7eb595caa38ced024a42ba1602d69e0387b8e3a1

### PR DESCRIPTION
**Pull request by alexhenrie**
Fixes #3761

I am not sure that this solution is entirely correct, but it's probably an improvement over the status quo.

### CODE REVIEW

**Comment by micheleCTDE** [comment]
@dbartolini 
Daniele, are you able to test this before we merge it?

**Comment by dbartolini** [comment]
It does the trick for me.

**Review by micheleCTDEAdmin — APPROVED** [review]
Looks good, thanks

**Comment by micheleCTDEAdmin** [comment]
> It does the trick for me.

Thanks for testing, Daniele!

**Pull request merged**
