### PR TITLE
Looking for a way to run some extra tests

### PR DESCRIPTION
**Pull request by guy-maurel**
Each test will have a different option line, with less or more options.
Some tests will produce a crash.
Home to do it better as with a bash shell?

### CODE REVIEW

**Comment by mwoehlke-kitware** [comment]
#1910 seems to be relevant.

I'd definitely prefer to see this implemented somehow as part of the testing framework, ideally with something like the `.test` files specifying sets of tests. I'm sure we could mark expected failure modes in here somehow.

What sorts of tests are you looking to add?

**Comment by guy-maurel** [comment]
I am working on the results from coveralls.
I see at many places that not any tests produce any trace at some lines.
This comes because the current test-script do not allowed all the ways we may use uncrustify.
We also need something for malformed commands, which may produce a crash.

**Comment by mwoehlke-kitware** [comment]
Let's move this discussion to #1910. I have some more thoughts that I will post there shortly.

In the meanwhile, if you're feeling impatient, I think it would be reasonable in the short term to add new things to `test_cli_options.py` for now, and later we can "port" them per #1910.

**Comment by guy-maurel** [comment]
Well, I am not impatient, but `test_cli_options.py` is not the same as `ctest`.
I prefer `ctest`, because of the test `coveralls` which show me where another test data is necessary.

**Comment by guy-maurel** [comment]
My goal is to see the coverage.
Having a look to the result from PR #1972, we get a Report for Build 2535. Looking for output.cpp at line 417 (https://coveralls.io/builds/18613023/source?filename=src%2Foutput.cpp#L417), we can see: the line is not covered.
The same with PR #1988, we get a Report for Build 2557. (https://coveralls.io/builds/18655092/source?filename=src/output.cpp#L417). The line is covered.
This is what I wanted to get.
Why the difference?

**Comment by mwoehlke-kitware** [comment]
D'oh! I guess coveralls runs on a debug build? I forgot, `test_cli_options.py` only runs on release builds. (We really should fix that. The reason it only runs on release has to do with some output where the debug builds dump call stacks, which then don't match the expected output. But it should be possible to munge the output to handle this. That's one of the things that is notionally on my #1910 list.)

**Comment by mwoehlke-kitware** [comment]
Another possibility could be to make the trace stuff dependent on something other than `_DEBUG` and tie it to a CMake option with a warning that turning on said option will cause spurious test failures... This would be less useful, but easier to implement.

**Comment by guy-maurel** [comment]
If `test_cli_options.py` works with `coveralls`, we can close this PR.

**Comment by mwoehlke-kitware** [comment]
> If `test_cli_options.py` works with coveralls, we can close this PR.

Done, in #1990: https://coveralls.io/builds/18657908/source?filename=src/output.cpp#L419.

**Comment by gmaurel** [comment]
@mwoehlke-kitware your solution is the better one, thanks.

**Pull request closed without merging**
