### PR TITLE
Fix installation directory for example config files

### PR DESCRIPTION
**Pull request by AMDmi3**
As per discussion in https://github.com/uncrustify/uncrustify/commit/ea6950086657de0ad12bc098f169a992407889ca

### CODE REVIEW

**Comment by mcatanzaro** [comment]
> `/usr/share/examples` is not specified by [the FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html). Per [this](https://www.tldp.org/HOWTO/HighQuality-Apps-HOWTO/fhs.html) (and also judging by `find /usr/share -type d -name examples` as run on my machine), I think `CMAKE_INSTALL_DOCDIR}/examples` (i.e. `/usr/share/doc/uncrustify/examples`) would be more typical.

I would do either `/usr/share/doc/uncrustify/examples` or perhaps `/usr/share/uncrustify/examples`.

I fear `/usr/share/examples/uncrustify` is rather too original. :) My instinct as a packager would be to convert that to `/usr/share/uncrustify/examples`.

**Comment by AMDmi3** [comment]
> `/usr/share/examples` is not specified by [the FHS](https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html).

Hmm, this is a surprise to me, now I see it's not supported neither of configure scripts, GNUInstallDirs.cmake and FHS. On FreeBSD, it's standard though:

https://github.com/freebsd/freebsd-ports/blob/master/Mk/bsd.port.mk#L883

Well, as long as there's consensus that it shouldn't go neither into DATADIR nor ETCDIR, it's fine in DOCSDIR too.

**Comment by AMDmi3** [comment]
Ping? We need to come to consensus in this to avoid files jumping around the filesystem on package updates for users.

**Comment by gmaurel** [comment]
@mwoehlke-kitware : could you please take it and decide?

**Comment by mwoehlke-kitware** [comment]
Sorry, I think I missed an update...

**Pull request merged**
