### PR TITLE
add appveyor.yml

### LINKED ISSUE #538: add PR testing on Windows
As a follow up of #470 it would be good to run the tests on Windows, too.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #538.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
This did not pass AppVeyor yet. The idea was to only merge this once it passes the tests on Windows.

**Comment by mihaipopescu** [comment]
Could you also add a status build badge on README.md https://www.appveyor.com/docs/status-badges ?

**Comment by dirk-thomas** [comment]
Please see #617 for the badge.

**Comment by mihaipopescu** [comment]
Awesome ! Thank you @dirk-thomas.

**Pull request merged**
