### PR TITLE
Avoid dereferencing NULL pointers

### PR DESCRIPTION
**Pull request by jibsen**
This is the fix mentioned in #916.

### CODE REVIEW

**Comment by mihaipopescu** [comment]
A null pointer check is more often than not a change to refrain from doing while fixing crashes. It is, as you also mentioned, a way of postponing or moving the crash to another place. A null check is the easy fix to do but that's local patching and not fixing the real issue.

In this case, if we take a step back and see where it's the real issue we could see that:

1. It appears that the crash first happens in C#-only option and we could be dealing with a non C# code
2. The issue in #916 we're dealing with partial for loop. Uncrustify does a pretty good job formatting uncompilable code most of the times but when it doesn't it crashes. We need Uncrustify to detect these cases (like the one with unmatched close brace) and complain about it (fail formatting) and modify the testing framework to support regression testing of failures as well.

**Comment by jibsen** [comment]
I agree, this just fixes the symptom.

Would you prefer I close this and you can open an issue for the general problem?

**Comment by gmaurel** [comment]
Both aspects are important.
As uncrustify could be call wilt a fragment ```--frag``` I find the PR is fine.

**Comment by mihaipopescu** [comment]
No, I think this PR is fine but it could use a test as well.

**Pull request merged**
